---
- name: install logwatch
  apt:
    name: logwatch
    state: latest

- name: create conf/logfiles directory
  file:
    path: /etc/logwatch/conf/logfiles
    state: directory
    mode: 0755

- name: create conf/services directory
  file:
    path: /etc/logwatch/conf/services
    state: directory
    mode: 0755

- name: create conf/html directory
  file:
    path: /etc/logwatch/conf/html
    state: directory
    mode: 0755

- name: create scripts/services directory
  file:
    path: /etc/logwatch/scripts/services
    state: directory
    mode: 0755

- name: install logwatch config
  template:
    src: logwatch.conf
    dest: /etc/logwatch/conf/logwatch.conf
    mode: "0664"

- name: install logwatch override config
  copy:
    src: files/override.conf
    dest: /etc/logwatch/conf/override.conf
    mode: "0664"

- name: install logwatch ignore file
  copy:
    src: files/ignore.conf
    dest: /etc/logwatch/conf/ignore.conf
    mode: "0664"
