
http:
  routers:

    # nextcloudhttp_route:
    #   entryPoints:
    #   - "http"
    #   middlewares:
    #   - https_redirect
    #   service: nextcloud_service
    #   rule: "Host(`nextcloud.{{dns_domain}}`)"

    nextcloud_route:
      entryPoints:
      - "websecure"
      service: nextcloud_service
      middlewares:
        - nextcloud-caldav
        - secheaders
      rule: "Host(`nextcloud.{{dns_domain}}`)"
      tls: 
        certResolver: letsencrypt

  services:
    nextcloud_service:
      loadBalancer:
        servers:
        - url: "http://{{hostname}}.{{dns_domain}}:8081/"

  middlewares:
    nextcloud-caldav:
      redirectRegex:
        permanent: true
        regex: "^https://(.*)/.well-known/(card|cal)dav"
        replacement: "https://$1/remote.php/dav/"
    secheaders:
      headers:
        stsSeconds: "315360000"
