---



- name: copy traefik config files
  template:
    src: "{{item}}"
    dest: /srv/traefik/conf/{{item}}
    mode: '0644'
    owner: root
    group: root
  with_items:
    - whoami.yml

- name: whoami container
  containers.podman.podman_container:
    name: whoami
    image: "docker.io/traefik/whoami"
    state: started
    network: external-net
    ports:
      - "8080:80"
