
- name: Copy nextcloud backup script
  template:
    src: nextcloud_backup.sh
    dest: /usr/local/bin/nextcloud_backup.sh
    mode: "0755"


- name: schedule nextcloud backup
  cron:
    name: "nextcloud backup"
    minute: "30"
    hour: "0"
    job: "/usr/local/bin/nextcloud_backup.sh || /usr/local/bin/telegram-notify --quiet --error --text 'Nextcloud backup failed'"
    cron_file: nextcloud_backup
    user: root
