



- name: "Pull image {{ nextcloud_image }}"
  containers.podman.podman_image:
    name: "{{ nextcloud_image }}"


- name:  Create podman container-nextcloud
  containers.podman.podman_container:
    name: nextcloud
    image: "{{ nextcloud_image }}"
    pod: nextcloud-pod
    state: started
    # publish:
    #   - "8081:80"
    # command: /bin/sh
    # entrypoint: /bin.sh
    volumes:
      - "{{nextcloud_datadir}}/html:/var/www/html"
      - "{{nextcloud_datadir}}/data:/var/www/html/data"
      - "{{nextcloud_datadir}}/config:/var/www/html/config"
    env:
      PGSQL_HOST: 127.0.0.1
      PGSQL_DB: "{{ nextcloud_pgsql_database }}"
      PGSQL_USER: "{{ nextcloud_pgsql_user }}"
      PGSQL_PASSWORD: "{{ nextcloud_pgsql_password }}"
      NEXTCLOUD_ADMIN_USER: "{{nextcloud_admin_user}}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{nextcloud_admin_password}}"
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.{{dns_domain}}"
      NEXTCLOUD_DATA_DIR: "/var/www/html/data"
      MAIL_FROM_ADDRESS: "nextcloud"
      MAIL_DOMAIN: "{{mail_domain}}"
      SMTP_HOST: "gollum.home"
      SMTP_PORT: 1587
      REDIS_HOST: 127.0.0.1
      OVERWRITEPROTOCOL: "https"
      TRUSTED_PROXIES: "traefik"
      REDIS_HOST_PASSWORD: "{{nextcloud_redis_password}}"
    label:
      io.containers.autoupdate: "image"


- name: Systemd Timer file to run nextcloud cron job
  template:
    src: nextcloud_cron.timer
    dest: "$HOME/.config/systemd/user/nextcloud_cron.timer"

- name: Systemd Service file to run nextcloud cron job
  template:
    src: nextcloud_cron.service
    dest: "$HOME/.config/systemd/user/nextcloud_cron.service"

# - name: Systemd - enable nextcloud timer
#   systemd:
#     name: nextcloud_cron.timer
#     daemon_reload: yes
#     enabled: yes
#     state: started
#     scope: user