



- name: Call destroy container nextcloud-pgsql
  vars:
    containers_shared_name: "nextcloud-pgsql"
    containers_shared_scope: "system"
  include_tasks: ../../shared-tasks/destroy-container.yml

- name: "Pull image {{ nextcloud_pgsql_image }}"
  containers.podman.podman_image:
    name: "{{ nextcloud_pgsql_image }}"

- name: Create podman container-nextcloud-pgsql
  containers.podman.podman_container:
    name: "nextcloud-pgsql"
    image: "{{ nextcloud_pgsql_image }}"
    state: started
    restart_policy: unless-stopped
    network: nextcloud-net
    volumes:
      - "{{ nextcloud_pgsql_data_volume }}:/var/lib/postgresql/data"
    env:
      POSTGRES_DB: "{{ nextcloud_pgsql_database }}"
      POSTGRES_USER: "{{ nextcloud_pgsql_user }}"
      POSTGRES_PASSWORD: "{{ nextcloud_pgsql_password }}"
      TZ: "{{ timezone }}"
    label:
      io.containers.autoupdate: "image"
  register: nextcloud_db_status

- name: wait for postgres to become ready
  shell: "podman logs --since=2m nextcloud-pgsql  2>&1 | grep 'port 5432'"
  register: result
  until: result.rc == 0
  when: nextcloud_db_status.changed
  retries: 45
  delay: 20

- name: Call create systemd container-nextcloud-pgsql
  vars:
    containers_shared_name: "nextcloud-pgsql"
    containers_shared_scope: "system"
    containers_shared_path: "/etc/systemd/system"
  include_tasks: ../../shared-tasks/create-systemd-container.yml

- name: Start systemd container-nextcloud-pgsql
  systemd:
    name: container-nextcloud-pgsql
    daemon_reload:  yes
    enabled: yes
    scope: system
    state: started
