




- name: "Pull image {{ nextcloud_pgsql_image }}"
  containers.podman.podman_image:
    name: "{{ nextcloud_pgsql_image }}"

- name: Create podman container-nextcloud-pgsql
  containers.podman.podman_container:
    name: "nextcloud-db"
    image: "{{ nextcloud_pgsql_image }}"
    pod: nextcloud-pod
    state: started
    volumes:
      - "{{ nextcloud_pgsql_data_volume }}:/var/lib/postgresql/data"
    env:
      POSTGRES_DB: "{{ nextcloud_pgsql_database }}"
      POSTGRES_USER: "{{ nextcloud_pgsql_user }}"
      POSTGRES_PASSWORD: "{{ nextcloud_pgsql_password }}"
      TZ: "{{ timezone }}"
    label:
      io.containers.autoupdate: "image"
  register: nextcloud_db_status

- name: wait for postgres to become ready
  shell: "podman logs --since=2m nextcloud-db  2>&1 | grep 'port 5432'"
  register: result
  until: result.rc == 0
  when: nextcloud_db_status.changed
  retries: 45
  delay: 20

