


- name: "Pull image  {{ nextcloud_redis_image }}"
  containers.podman.podman_image:
    name: "{{ nextcloud_redis_image }}"


- name: Create podman container-nextcloud-redis
  containers.podman.podman_container:
    name: "nextcloud-redis"
    pod: nextcloud-pod
    image: "{{ nextcloud_redis_image }}"
    state: started
    command: redis-server --requirepass {{nextcloud_redis_password}}
    label:
      io.containers.autoupdate: "image"

