

---
- name: dump vars
  hosts: fileserver
  remote_user: deploy
  become: true
  gather_facts: true


  tasks:
    # - name: print variables
    #   debug: msg="{{ lookup('vars',  item) }}"
    #   loop:
    #     - vaultwarden_admin_token


    - name: get ubuntu user groups
      shell: id -Gn ubuntu | tr ' ' ','
      register: ubuntu_groups

    - debug: msg="{{ubuntu_groups.stdout.split(' ')[1:] }}"
    # - debug: msg="{{ubuntu_groups.stdout | map("split", " ") }}"
