- name: a playbook to configure my dhcp/dns server
  hosts: dnsserver
  remote_user: deploy
  become: true


  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml
    - ~/.private/ansible/vars/gpg-privkey.vault.yml
    - vars/gpg-pubkey.vault.yml
    - vars/telegram.vault.yml
    # - vars/nextcloud-client.vault.yml

  handlers:
  - include: handlers/reboot.yml

  roles:
    # - setup-raspbian
    # - geerlingguy.security
    # - packages
    # - logwatch
    # - unattended-upgrades-raspbian
    # - gpg
    - telegram


    # - email
    # - dotfiles
    # - motd
    # - nextcloud-client-tools
    # - certbot-gandi-dns
    # - ssh-certs

  tasks:

    - cron:
        name: "Auto nightly reboot"
        minute: "15"
        hour: "3"
        job: "/sbin/shutdown -r now"
        cron_file: reboot
        user: root


