- name: a playbook to configure smaug.local
  hosts: dnsserver_local
  remote_user: deploy
  become: true

  handlers:
  - include: handlers/reboot.yml

  roles:
    - role: setup-raspbian   
      vars:
        static_nameserver_addresses: ["{{static_ipv4_gateway}}"]
    - geerlingguy.security

  tasks:

    - name: Run the equivalent of "apt dist-upgrade"
      apt:
        update_cache: no
        upgrade: dist
      notify: reboot and wait

    - name: install new packages
      apt:
        name: "{{all_packages}}"
        state: latest
      notify: reboot and wait

