

- name: a playbook to configure gollum.home
  hosts: fileserver
  remote_user: deploy
  become: true

  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml
    - ~/.private/ansible/vars/gpg-privkey.vault.yml
    - vars/gpg-pubkey.vault.yml
    - vars/telegram.vault.yml
    - vars/ssh-certs.vault.yml
    - vars/vault.yml
    # - vars/samba.vault.yml
    # - vars/vaultwarden.vault.yml


  handlers:
    - include: handlers/reboot.yml

  collections:
    - ejsmit.containers

  roles:
    # - setup-ubuntu-pi
    # - geerlingguy.security
    # - packages
    # - gpg
    # - telegram
    # - file-tools
    # - postfix-relay
    # - logwatch
    # - ssh-certs
    # now run: sudo zpool import -f bigdata
    - podman
    - samba-pi




    # - dotfiles
    # - motd

    # - traefik
    # - syncthing
    # - nextcloud
    # - vaultwarden
    # - minio



  tasks:


# --------------------------
#   forced reboot
# --------------------------

  # - debug: msg="Trigger Reboot"
  #   notify: reboot and wait
  #   changed_when: true
